src/main/java/org/dwcj/controls/Button.java

1) I wanted to try a quick pull request just to make sure I have the process down correctly.
2) I updated this method, though I wasn't sure whether or not this one should be chained, as the rest of the setters for this 
component were correctly returning "this". If this function doesn't need to be chained, kindly ignore this :)

Updated setDisableOnClick to return this for method chaining

---

src/main/java/org/dwcj/controls/BarChart.java
src/main/java/org/dwcj/controls/CheckableMenuItem.java
src/main/java/org/dwcj/controls/ComboBox.java
src/main/java/org/dwcj/controls/FontChooser.java
src/main/java/org/dwcj/controls/HtmlContainer.java
src/main/java/org/dwcj/events/sinks/combobox/BBjComboBoxSelectEventSink.java

FontChooser, HTMLContainer to return this. Fixed copy paste error in BarChart to correct the X axis label. Initiated the targets member in ComboBoxSelectEventSink.

Fixed more setters in BarChart, CheckableMenuItem, ComboBox, 

---

pom.xml
src/main/java/org/dwcj/events/htmlcontainer/HtmlContainerOnScriptLoadedEvent.java
src/main/java/org/dwcj/events/sinks/htmlcontainer/HtmlContainerOnScriptLoadedEventSink.java

included pom.xml and removed console messages

Branch matthew two

---

src/main/java/org/dwcj/controls/CtrlAccessorImpl.java

fix: CtrlAccessorImpl::create does not traverse the control parent classes

---

pom.xml
src/main/java/org/dwcj/controls/panels/AppPanel.java

fix https://github.com/DwcJava/engine/issues/144

---

src/main/java/org/dwcj/controls/panels/AppPanel.java
src/main/java/org/dwcj/controls/panels/Div.java

Tried the following code, and instead us utilizing the conditions, I directly changed the flag's values, and the AppPanel which displays the various programs would not display. For now, only the Div has been modified to honor creation flags.
```java
// this.setVisible(false);
byte finalFlag = (byte) 0x88;
if(Boolean.FALSE.equals(this.isVisible())){
finalFlag += (byte) 0x10;
}
if(Boolean.FALSE.equals(this.isEnabled())){
finalFlag += (byte) 0x20;
}
byte[] flags = new byte[]{(byte) 0x01, (byte) 0x11, (byte) 0x10, finalFlag};
```

116 apppanel and div creation flags should be updated

---

pom.xml
src/main/java/org/dwcj/annotations/AnnotationProcessor.java
src/main/java/org/dwcj/annotations/InlineJavaScript.java
src/main/java/org/dwcj/annotations/InlineStyleSheet.java
src/main/java/org/dwcj/annotations/JavaScript.java
src/main/java/org/dwcj/annotations/StyleSheet.java
src/main/java/org/dwcj/controls/applayout/AppLayout.java
src/main/java/org/dwcj/controls/applayout/events/AppLayoutDrawerClosedEvent.java
src/main/java/org/dwcj/controls/applayout/events/AppLayoutDrawerOpenedEvent.java
src/main/java/org/dwcj/controls/dialog/Dialog.java
src/main/java/org/dwcj/controls/dialog/events/DialogClosedEvent.java
src/main/java/org/dwcj/controls/dialog/events/DialogOpenedEvent.java
src/main/java/org/dwcj/controls/drawer/Drawer.java
src/main/java/org/dwcj/controls/drawer/events/DrawerClosedEvent.java
src/main/java/org/dwcj/controls/drawer/events/DrawerOpenedEvent.java
src/main/java/org/dwcj/environment/ObjectTable.java
src/main/java/org/dwcj/exceptions/DwcControlDestroyed.java
src/main/java/org/dwcj/webcomponent/PropertyDescriptor.java
src/main/java/org/dwcj/webcomponent/WebComponent.java
src/main/java/org/dwcj/webcomponent/annotations/EventExpressions.java
src/main/java/org/dwcj/webcomponent/annotations/EventName.java
src/main/java/org/dwcj/webcomponent/annotations/NodeAttribute.java
src/main/java/org/dwcj/webcomponent/annotations/NodeName.java
src/main/java/org/dwcj/webcomponent/annotations/NodeProperty.java
src/main/java/org/dwcj/webcomponent/events/Event.java
src/main/java/org/dwcj/webcomponent/events/EventDispatcher.java
src/main/java/org/dwcj/webcomponent/events/EventListener.java

1. The PR add a mini-framework to support integrating any arbitrary web component in dwcj.
2. Implement AppLayout component
3. Implement Drawer component
4. Add support for BBj ObjectTable
Note: The PR adds `com.google.code.gson` as a dependency

feat: Add support for webcomponents integration

---

src/main/resources/bbj/DwcjHelper.bbj
src/main/resources/bbj/dwcj.bbj

You can now add "debug" as command line argument in EM, or SET DEBUG=1 in your config.bbx file.

Improved error reporting

---

README.md
dwcj-code-widget/pom.xml
dwcj-engine/pom.xml
dwcj-markdown-widget/pom.xml
pom.xml

- no duplication
- prevent duplication of configuration of plugins etc.
- Move deps to parent (dependencyManagement)
- Changed the groupId to a common one might be changed if needed.

Monorepo Setup with multimodule build

---

dwcj-engine/src/main/java/org/dwcj/controls/tabcontrol/TabControl.java

Updated Tab Control with functionality needed for App Layout

---

dwcj-widgets/dwcj-googlecharts-widget/pom.xml
dwcj-widgets/dwcj-googlecharts-widget/src/main/java/org/dwcj/widgets/googlecharts/GoogleChart.java
dwcj-widgets/dwcj-googlecharts-widget/src/main/java/org/dwcj/widgets/googlecharts/events/GoogleChartReadyEvent.java
dwcj-widgets/dwcj-googlecharts-widget/src/main/java/org/dwcj/widgets/googlecharts/events/GoogleChartSelectedEvent.java
dwcj-widgets/pom.xml

```java
import org.dwcj.App;
import org.dwcj.annotations.InlineStyleSheet;
import org.dwcj.controls.panels.AppPanel;
import org.dwcj.exceptions.DwcException;
import org.dwcj.widgets.googlecharts.GoogleChart;
import com.google.gson.JsonArray;
import com.google.gson.JsonObject;
@InlineStyleSheet(value = /* css */"""
.app {
display: flex;
flex-direction: column;
align-items: center;
gap: 1rem;
padding: 2rem;
height: inherit
}
""")
public class PieChart extends App {
@Override
public void run() throws DwcException {
AppPanel panel = new AppPanel();
panel.addClassName("app");
GoogleChart chart = new GoogleChart();
chart.setType(GoogleChart.Type.PIE);
chart.setStyle("width", "800px");
chart.setStyle("height", "400px");
// options
// JsonObject options = new JsonObject();
JsonObject options = …
```

[feat] Add GoogleCharts widget

---

dwcj-engine/src/main/java/org/dwcj/App.java

mention @mhawkinsbasis for documentation.
```java
@Override
public void run() throws DwcException {
msgbox(String.valueOf(executeJs("1 + 1")));
executeAsyncJs("setTimeout(() =>  alert('Hello from DWCJ!'), 1000);");
}
}
```

feat: add `App.executeJs` and `App.executeAsyncJs` methods

---

dwcj-engine/src/main/java/org/dwcj/App.java

feat: add app methods to query the app information

---

dwcj-engine/src/main/java/org/dwcj/controls/panels/Div.java
dwcj-engine/src/main/java/org/dwcj/controls/panels/sinks/DivClickEventSink.java
dwcj-engine/src/main/java/org/dwcj/controls/textbox/TextBox.java

Closes #239 and closes #240
Test code:
```java
import org.dwcj.App;
import org.dwcj.controls.panels.AppPanel;
import org.dwcj.controls.panels.Div;
import org.dwcj.controls.panels.events.DivClickEvent;
import org.dwcj.controls.textbox.TextBox;
import org.dwcj.exceptions.DwcException;
public class Test extends App {
@Override
public void run() throws DwcException{
AppPanel p = new AppPanel();
Div test = new Div().setStyle("height", "500px").setStyle("width", "500px").setStyle("background", "red");
test.onClick(this::click1);
test.onClick(this::click2);
TextBox test2 = new TextBox();
test2.setReadOnly(true);
p.add(test2);
p.add(test);
}
private void click1(DivClickEvent ev){
App.consoleLog("Test 1");    
}
private void click2(DivClickEvent ev){
App.consoleLog("Test 2");
}
}
```

Catchup fixes

---

dwcj-engine/src/main/java/org/dwcj/controls/flexlayout/FlexAlignment.java
dwcj-engine/src/main/java/org/dwcj/controls/flexlayout/FlexContentAlignment.java
dwcj-engine/src/main/java/org/dwcj/controls/flexlayout/FlexDirection.java
dwcj-engine/src/main/java/org/dwcj/controls/flexlayout/FlexFlow.java
dwcj-engine/src/main/java/org/dwcj/controls/flexlayout/FlexJustifyContent.java
dwcj-engine/src/main/java/org/dwcj/controls/flexlayout/FlexLayout.java
dwcj-engine/src/main/java/org/dwcj/controls/flexlayout/FlexLayoutBuilder.java
dwcj-engine/src/main/java/org/dwcj/controls/flexlayout/FlexProperties.java
dwcj-engine/src/main/java/org/dwcj/controls/flexlayout/FlexWrap.java

> I'm not certain whether we should integrate this feature into the engine or offer it as a standalone widget. However, I can see the advantages of incorporating it into the engine.
The pull request introduces a new control that enables Java developers to create fileable layouts directly from Java code, without the need to work with CSS directly. This control features a declarative builder interface that allows for the composition of complex layouts with just a few lines of code. 
The flex layout control is built upon the `Div` control and draws inspiration from the [Vaadin Basic Layouts](https://vaadin.com/docs/latest/components/basic-layouts). For visual documentation, you can refer to [CSS Tricks](https://css-tricks.com/snippets/css/a-guide-to-flexbox/).
For instance: 
```java …
```

feat: add flexlayout component

---

pom.xml

```java
package org.dwcj;
import static org.junit.jupiter.api.Assertions.assertEquals;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.ValueSource;
class CalculatorTests {
@Test
@DisplayName("1 + 1 = 2")
void addsTwoNumbers() {
// Calculator calculator = new Calculator();
assertEquals(2, 1 + 1, "1 + 1 should equal 2");
}
@ParameterizedTest
@ValueSource(ints = {1, 3, 5, -3, 15, Integer.MAX_VALUE}) // six numbers
void isOdd_ShouldReturnTrueForOddNumbers(int number) {
assertEquals(true, number % 2 != 0);
}
}
```

chore: configure junit5

---

dwcj-engine/src/main/java/org/dwcj/component/AbstractDwcComponent.java
dwcj-engine/src/main/java/org/dwcj/component/HasProperty.java

Added a HasProperty interface with the methods for putting a property and getting a property. Then implemented said 
interface for the AbstractDwcComponent.
Closes #152

added HasProperty interface and implemented it for abstractdwccomponent

---

dwcj-engine/src/main/java/org/dwcj/component/event/BlurEvent.java
dwcj-engine/src/main/java/org/dwcj/component/event/FocusEvent.java

removed AbstractDwcComponent type from Event<> and Constructor with AbstractComponent

refactor: Blur/FocusEvent

---

dwcj-engine/src/main/java/org/dwcj/component/label/Label.java

Added an override for the setProperty method so its chainable.

fix: added setProperty override for chaining

---

dwcj-engine/src/main/java/org/dwcj/bridge/ComponentAccessor.java
dwcj-engine/src/main/java/org/dwcj/component/AbstractComponent.java
dwcj-engine/src/main/java/org/dwcj/component/AbstractDwcComponent.java
dwcj-engine/src/main/java/org/dwcj/component/ComponentAccessorImpl.java
dwcj-engine/src/main/java/org/dwcj/component/label/Label.java

Refactored the AbstractComponent and AbstractDwcComponent so the BBjControl is now a member in AbstractDwcComponent but only package private so that the Accessor is needed to get to it.

feat: refactored ctrl to be in AbstractDwcComponent

---

dwcj-engine/src/main/java/org/dwcj/component/button/AbstractButton.java
dwcj-engine/src/main/java/org/dwcj/component/button/Button.java
dwcj-engine/src/main/java/org/dwcj/component/button/ButtonTheme.java
dwcj-engine/src/main/java/org/dwcj/component/button/event/ButtonClickEvent.java
dwcj-engine/src/main/java/org/dwcj/component/button/sink/ButtonClickEventSink.java
dwcj-engine/src/test/java/org/dwcj/component/button/AbstractButtonMock.java
dwcj-engine/src/test/java/org/dwcj/component/button/AbstractButtonTest.java
dwcj-engine/src/test/java/org/dwcj/component/button/ButtonTest.java
dwcj-engine/src/test/java/org/dwcj/component/button/event/ButtonClickEventTest.java

@mhawkinsbasis  After this PR. The code in the readme file should be updated:
```java
Button btn = new Button("Say Hello");
btn.setTheme(Button.Theme.SUCCESS)
.setExpanse(Button.Expanse.XLARGE)
.onClick(e -> msgbox("Hello World!"));
```

feat: implement button component

---

dwcj-engine/src/main/java/org/dwcj/component/button/AbstractButton.java
dwcj-engine/src/test/java/org/dwcj/component/button/AbstractButtonTest.java

feat: `Button` should implement `setName`/`getName` methods

---

dwcj-engine/src/main/java/org/dwcj/component/DwcComponent.java
dwcj-engine/src/main/java/org/dwcj/concern/HasProperty.java
dwcj-engine/src/test/java/org/dwcj/component/DwcComponentTest.java
dwcj-engine/src/test/java/org/dwcj/component/DwcFocusableComponentTest.java
dwcj-engine/src/test/java/org/dwcj/component/field/DwcFieldTest.java
dwcj-engine/src/test/java/org/dwcj/component/field/DwcTextFieldTest.java
dwcj-engine/src/test/java/org/dwcj/component/field/NumberFieldTest.java
dwcj-engine/src/test/java/org/dwcj/component/list/DwcSelectDropdownTest.java
dwcj-engine/src/test/java/org/dwcj/component/optioninput/CheckBoxTest.java
dwcj-engine/src/test/java/org/dwcj/component/optioninput/RadioButtonTest.java

@MatthewHawkins please check the docs , and your demos for any issues

feat: enhance getProperty with type casting for returned values

---

dwcj-engine/src/main/java/org/dwcj/component/Component.java
dwcj-engine/src/test/java/org/dwcj/component/ComponentTest.java

The method returns a PendingResult}that completes when the component is attached in the DOM.

feat: add `Component::whenAttached` method

---

dwcj-engine/src/main/java/org/dwcj/App.java
dwcj-engine/src/main/java/org/dwcj/AppCloseAction.java
dwcj-engine/src/main/java/org/dwcj/DefaultAction.java
dwcj-engine/src/main/java/org/dwcj/MessageAction.java
dwcj-engine/src/main/java/org/dwcj/NoneAction.java
dwcj-engine/src/main/java/org/dwcj/RedirectAction.java
dwcj-engine/src/test/java/org/dwcj/AppTest.java
dwcj-engine/src/test/java/org/dwcj/MessageActionTest.java
dwcj-engine/src/test/java/org/dwcj/RedirectActionTest.java

Sample:
```java
setTerminateAction(new RedirectAction("https://www.google.com"));
setTerminateAction(new MessageAction("Bye Bye!"));
setTerminateAction(DEFAULT_ACTION);
setTerminateAction(NONE_ACTION);
setTerminateAction(RELAUNCH_ACTION);
```

feat: implement App Terminate and Error close actions

---

dwcj-engine/src/main/java/org/dwcj/component/layout/applayout/AppLayout.java
dwcj-engine/src/test/java/org/dwcj/component/layout/applayout/AppLayoutTest.java

@MatthewHawkins please update the AppLayout docs, the PR:
1. Remove style method (drawerWidth). Css variables must be used for this (Keep the current docs, just explain the way to do it with css variables)
2. Add support for the drawer title, header-actions and footer slots
3. add new methods : `setDrawerHeaderVisible` , `setDrawerFooterVisible`
```java
public class AppLayoutDemo extends App {
AppLayout demo = new AppLayout();
Label contentLabel = new Label();
Panel header = new Panel();
Panel drawer = new Panel();
@Override
public void run() throws DwcjException {
Frame window = new Frame();
window.add(demo);
demo.setDrawerHeaderVisible(true);
demo.setDrawerFooterVisible(true);
demo.addToDrawerTitle(new Div("Menu"));
demo.addToDrawerHeaderActions(new …
```

refactor(applayout): add new drawer slots

---

dwcj-engine/src/main/java/org/dwcj/component/tabbedpane/Tab.java
dwcj-engine/src/main/java/org/dwcj/component/tabbedpane/TabChangeListener.java
dwcj-engine/src/main/java/org/dwcj/component/tabbedpane/TabbedPane.java
dwcj-engine/src/main/java/org/dwcj/component/tabbedpane/event/TabCloseEvent.java
dwcj-engine/src/main/java/org/dwcj/component/tabbedpane/event/TabDeselectEvent.java
dwcj-engine/src/main/java/org/dwcj/component/tabbedpane/event/TabEvent.java
dwcj-engine/src/main/java/org/dwcj/component/tabbedpane/sink/TabCloseEventSink.java
dwcj-engine/src/main/java/org/dwcj/component/tabbedpane/sink/TabDeselectEventSink.java
dwcj-engine/src/test/java/org/dwcj/component/DwcComponentMock.java
dwcj-engine/src/test/java/org/dwcj/component/tabbedpane/TabbedPaneTest.java
dwcj-engine/src/test/java/org/dwcj/component/tabbedpane/event/TabCloseEventTest.java
dwcj-engine/src/test/java/org/dwcj/component/tabbedpane/event/TabDeselectEventTest.java
dwcj-engine/src/test/java/org/dwcj/component/tabbedpane/event/TabSelectEventTest.java

@MatthewHawkins, please review the JavaDocs and ensure everything is in optimal condition. Additionally, you will need to update the documentation site. This update is scheduled for `23.06`, which is set to release on January 22, 2024.
For reference, the [DWCJ Component Progress](https://docs.google.com/spreadsheets/d/1Wd2JEGPBwnyEiSR9xf0VJxMJY_GMPWoS6omgVzvLlEc/edit?usp=sharing) spreadsheet outlines the features that have been implemented and those planned for future releases.

feat: Implement `TabbedPane`

---

dwcj-engine/src/main/java/org/dwcj/component/element/ElementComposite.java
dwcj-engine/src/main/java/org/dwcj/component/element/annotation/ElementAnnotationProcessor.java
dwcj-engine/src/main/java/org/dwcj/component/html/HtmlComponent.java
dwcj-engine/src/main/java/org/dwcj/component/html/event/HtmlClickEvent.java
dwcj-engine/src/main/java/org/dwcj/dispatcher/EventDispatcher.java
dwcj-engine/src/main/java/org/dwcj/dispatcher/ListenerRegistration.java
dwcj-engine/src/test/java/org/dwcj/component/element/ElementCompositeTest.java

@MatthewHawkins, there's a last-minute change that needs to be completed before the release on 23.06. Please verify that the events are functioning as expected in the documentation and inform me once you have confirmed this.
fixes #491

fix: EventDispatcher does not allow events which utilize Generics

---

dwcj-engine/src/main/java/org/dwcj/component/list/ListBox.java
dwcj-engine/src/main/java/org/dwcj/component/list/MultipleSelectableList.java
dwcj-engine/src/main/java/org/dwcj/component/list/SelectableList.java
dwcj-engine/src/main/java/org/dwcj/component/list/event/ListEvent.java
dwcj-engine/src/main/java/org/dwcj/data/selection/MultipleSelectable.java
dwcj-engine/src/main/java/org/dwcj/data/selection/Selectable.java
dwcj-engine/src/main/java/org/dwcj/data/selection/SingleSelectable.java
dwcj-engine/src/main/java/org/dwcj/data/selection/event/AbstractSelectEvent.java
dwcj-engine/src/main/java/org/dwcj/data/selection/event/SelectEvent.java
dwcj-engine/src/test/java/org/dwcj/component/list/ListBoxTest.java

BREAKING CHANGE:
1. rename `ListBox:selectKeys` to `ListBox:selectKey`
2. rename `ListBox:selectIndices` to `ListBox:selectIndex`
@MatthewHawkins please go over the javadocs

feat: implement selection model

---

dwcj-engine/src/main/java/org/dwcj/data/EntityKeysRegistry.java
dwcj-engine/src/main/java/org/dwcj/data/HasEntityKey.java
dwcj-engine/src/main/java/org/dwcj/data/repository/AbstractRepository.java
dwcj-engine/src/main/java/org/dwcj/data/repository/CollectionRepository.java
dwcj-engine/src/main/java/org/dwcj/data/repository/CompositeComparator.java
dwcj-engine/src/main/java/org/dwcj/data/repository/HasRepository.java
dwcj-engine/src/main/java/org/dwcj/data/repository/OrderCriteria.java
dwcj-engine/src/main/java/org/dwcj/data/repository/OrderCriteriaList.java
dwcj-engine/src/main/java/org/dwcj/data/repository/Repository.java
dwcj-engine/src/main/java/org/dwcj/data/repository/RetrievalBuilder.java
dwcj-engine/src/main/java/org/dwcj/data/repository/RetrievalCriteria.java
dwcj-engine/src/main/java/org/dwcj/data/repository/event/RepositoryCommitEvent.java
dwcj-engine/src/main/java/org/dwcj/data/selection/event/RepositorySelectEvent.java
dwcj-engine/src/main/java/org/dwcj/data/selection/repository/MultipleSelectableRepository.java
dwcj-engine/src/main/java/org/dwcj/data/selection/repository/SelectableRepository.java
dwcj-engine/src/main/java/org/dwcj/data/selection/repository/SingleSelectableRepository.java
dwcj-engine/src/test/java/org/dwcj/data/EntityKeysRegistryTest.java
dwcj-engine/src/test/java/org/dwcj/data/repository/CollectionRepositoryTest.java
dwcj-engine/src/test/java/org/dwcj/data/repository/CompositeComparatorTest.java
dwcj-engine/src/test/java/org/dwcj/data/repository/OrderCriteriaListTest.java
dwcj-engine/src/test/java/org/dwcj/data/repository/OrderCriteriaTest.java
dwcj-engine/src/test/java/org/dwcj/data/repository/RetrievalBuilderTest.java
dwcj-engine/src/test/java/org/dwcj/data/selection/MultipleSelectableComponentMock.java
dwcj-engine/src/test/java/org/dwcj/data/selection/MultipleSelectableTest.java
dwcj-engine/src/test/java/org/dwcj/data/selection/SelectableComponentMock.java
dwcj-engine/src/test/java/org/dwcj/data/selection/SelectableTest.java
dwcj-engine/src/test/java/org/dwcj/data/selection/event/RepositorySelectEventTest.java

@MatthewHawkins please go over the javadocs

feat: Introduce a new model for unified data retrieval and counting

---

webforj-components/pom.xml
webforj-components/webforj-splitter/pom.xml
webforj-components/webforj-splitter/src/main/java/com/webforj/component/layout/splitter/Splitter.java
webforj-components/webforj-splitter/src/main/java/com/webforj/component/layout/splitter/event/SplitterResizeEvent.java
webforj-components/webforj-splitter/src/test/java/com/webforj/component/layout/splitter/SplitterTest.java
webforj/pom.xml

@MatthewHawkins please go over the docs

feat: add splitter component

---

pom.xml
webforj-foundation/src/main/java/com/webforj/environment/namespace/CanLock.java
webforj-foundation/src/main/java/com/webforj/environment/namespace/Namespace.java
webforj-foundation/src/main/java/com/webforj/environment/namespace/NamespaceVarableLockedException.java
webforj-foundation/src/main/java/com/webforj/environment/namespace/NamespaceVariableLockedException.java
webforj-foundation/src/main/java/com/webforj/environment/namespace/StandardNamespace.java

NamespaceVarableLockedException -> NamespaceVARIABLELockedException.
typo fixed.

Namespace Exception typo fixed

---

CONTRIBUTING.md

chore: fixing image links

---

webforj-plugins/webforj-install-bbj-plugin/src/main/java/com/webforj/installer/WebforjInstaller.java

Depends on https://github.com/BBj-Plugins/DWCJ/pull/14

feat: deployed apps should use _webforj_default classpath

---

webforj-foundation/src/main/java/com/webforj/component/progressbar/ProgressBar.java
webforj-foundation/src/test/java/com/webforj/component/progressbar/ProgressBarTest.java

@MatthewHawkins please go over the java docs and fix any obvious issues.

feat: implement ProgressBar 

---

.vscode/settings.json
webforj-foundation/src/main/java/com/webforj/App.java
webforj-foundation/src/main/java/com/webforj/BrowserConsole.java
webforj-foundation/src/test/java/com/webforj/BrowserConsoleTest.java

The PR introduces a dedicated utility class that can be accessed statically through the `App` class to log styled messages to the browser console.
see #494
```java
import com.webforj.App;
import com.webforj.Environment;
import com.webforj.exceptions.WebforjException;
@Override
console().log(Environment.getCurrent().isDebug(), true);
// Types
console().log("Log message");
console().info("Info message");
console().warn("Warn message");
console().error("Error message");
console().debug("Debug message");
// font styles
console().style().italic().log("Font italic");
console().style().normal().log("Font normal");
// font weight
console().weight().lighter().log("Font Weight: lighter"); …
```

feat: add `BrowserConsole` to log styled browser log messages

---

webforj-components/webforj-html-elements/src/main/java/com/webforj/component/html/HtmlComponent.java
webforj-foundation/src/main/java/com/webforj/component/DwcComponent.java
webforj-foundation/src/main/java/com/webforj/concern/HasHeight.java
webforj-foundation/src/main/java/com/webforj/concern/HasMaxHeight.java
webforj-foundation/src/main/java/com/webforj/concern/HasMaxWidth.java
webforj-foundation/src/main/java/com/webforj/concern/HasMinHeight.java
webforj-foundation/src/main/java/com/webforj/concern/HasMinWidth.java
webforj-foundation/src/main/java/com/webforj/concern/HasSize.java
webforj-foundation/src/main/java/com/webforj/concern/HasWidth.java
webforj-foundation/src/test/java/com/webforj/component/DwcComponentTest.java
webforj-foundation/src/test/java/com/webforj/concern/ConcernComponentMock.java
webforj-foundation/src/test/java/com/webforj/concern/HasSizeTest.java

This PR add size concerns and adds support for configuring minSize, maxSize, and size for all HTML components and webforJ core components.

feat: allow size configuration for webforj components

---

webforj-foundation/src/main/java/com/webforj/App.java
webforj-foundation/src/main/java/com/webforj/BusyIndicator.java
webforj-foundation/src/main/java/com/webforj/component/loading/DwcLoading.java
webforj-foundation/src/main/java/com/webforj/component/spinner/DwcSpinner.java
webforj-foundation/src/main/java/com/webforj/component/spinner/SpinnerExpanse.java
webforj-foundation/src/test/java/com/webforj/AppTest.java
webforj-foundation/src/test/java/com/webforj/BusyIndicatorTest.java

The PR introduces the Application Busy Indicator component. This app-level loading overlay indicates when the application is busy or processing data, blocking user interaction until the process is complete.
```java
import com.webforj.App;
import com.webforj.BusyIndicator;
import com.webforj.Interval;
import com.webforj.component.Theme;
import com.webforj.component.spinner.SpinnerExpanse;
import com.webforj.dispatcher.EventListener;
import com.webforj.exceptions.WebforjException;
private int retry = 1;
@Override
// Advance configurations
BusyIndicator indicator = getBusyIndicator();
indicator.setText("Initiating spoon pending sequence... Hold tight! This will take 3 seconds.");
Interval interval = new …
```

feat: add application BusyIndicator

---

webforj-components/pom.xml
webforj-components/webforj-loading/pom.xml
webforj-components/webforj-loading/src/main/java/com/webforj/component/loading/Loading.java
webforj-components/webforj-loading/src/test/java/com/webforj/component/loading/LoadingTest.java
webforj-report-aggregate/pom.xml
webforj/pom.xml

The PR introduces the `webforj-loading` component. This component is similar to the  app `BusyIndicator` and uses the same client component. However, the `webforj-loading` component can have children and can be attached to any parent component, making it scoped to its parent.
```java
import com.webforj.App;
import com.webforj.component.button.Button;
import com.webforj.component.html.elements.Div;
import com.webforj.component.html.elements.Paragraph;
import com.webforj.component.layout.flexlayout.FlexLayout;
import com.webforj.component.window.Frame;
import com.webforj.exceptions.WebforjException;
import com.webforj.component.loading.Loading;
public class LoadingComponentSample extends App {
@Override
Frame mainFrame = new Frame();
Div div = new …
```

feat: add webforj-loading component

---

webforj-foundation/src/main/java/com/webforj/component/optioninput/CheckBox.java
webforj-foundation/src/main/java/com/webforj/component/optioninput/DwcOptionInput.java
webforj-foundation/src/main/java/com/webforj/component/optioninput/RadioButton.java
webforj-foundation/src/main/java/com/webforj/component/optioninput/RadioButtonGroup.java
webforj-foundation/src/test/java/com/webforj/component/optioninput/CheckBoxTest.java
webforj-foundation/src/test/java/com/webforj/component/optioninput/RadioButtonGroupTest.java
webforj-foundation/src/test/java/com/webforj/component/optioninput/RadioButtonTest.java

The PR introduces several new constructors in the `CheckBox`, `RadioButton`, and `RadioButtonGroup` components to align them with the available constructors in the field package.

feat: align optioninput constructors with field constructors

---

webforj-components/pom.xml
webforj-components/webforj-toast/pom.xml
webforj-components/webforj-toast/src/main/java/com/webforj/component/toast/Toast.java
webforj-components/webforj-toast/src/test/java/com/webforj/component/toast/ToastTest.java
webforj-report-aggregate/pom.xml
webforj/pom.xml

The PR adds the `Toast` component.
```java
Toast.show("Your session will expire in 5 minutes due to inactivity.", 5000, Theme.INFO);
// Or
Toast t = new Toast("", -1, Theme.GRAY);
t.add(
new Spinner(),
new Paragraph("System update failed. Restoring to the previous state."),
new Button("Stop", ButtonTheme.DANGER, e -> t.close())
);
```

feat: add webforj-toast component

---

webforj-components/pom.xml
webforj-components/webforj-columnslayout/pom.xml
webforj-components/webforj-columnslayout/src/main/java/com/webforj/component/layout/columnslayout/ColumnsLayout.java
webforj-components/webforj-columnslayout/src/test/java/com/webforj/component/layout/columnslayout/ColumnsLayoutTest.java
webforj-report-aggregate/pom.xml
webforj/pom.xml

The PR adds the `ColumnsLayout` component that provides a responsive layout with dynamic columns based on the width of the layout. It adjusts the number of columns automatically according to the specified breakpoints.
```java
public class ColumnsLayoutSample extends App {
TextField firstName = new TextField("First Name");
TextField lastName = new TextField("Last Name");
TextField email = new TextField("Email");
PasswordField password = new PasswordField("Password");
PasswordField confirmPassword = new PasswordField("Confirm Password");
Button submit = new Button("Submit", ButtonTheme.PRIMARY);
/*
* The layout will position the components in 2 columns by default.
*/
ColumnsLayout columnsLayout =
new ColumnsLayout(firstName, lastName, email, password, confirmPassword, submit);
@Override …
```

feat: add webforj-columnslayout component

---

webforj-foundation/src/main/java/com/webforj/BrowserConsole.java
webforj-foundation/src/test/java/com/webforj/BrowserConsoleTest.java
webforj-plugins/webforj-install-bbj-plugin/src/main/java/com/webforj/installer/WebforjInstaller.java

fix: `BrowserConsole` font-size: larger is smaller than font-size: large

---

webforj-components/webforj-html-elements/src/main/java/com/webforj/component/html/elements/Iframe.java
webforj-components/webforj-icons/src/main/java/com/webforj/component/icons/Icon.java
webforj-foundation/src/main/java/com/webforj/component/Composite.java
webforj-foundation/src/main/java/com/webforj/component/DwcComponent.java
webforj-foundation/src/main/java/com/webforj/component/field/DwcMaskedField.java
webforj-foundation/src/test/java/com/webforj/component/CompositeTest.java
webforj-foundation/src/test/java/com/webforj/component/DwcComponentTest.java

refactor: pass the component's name to the underlying BBj controls

---

webforj-components/webforj-applayout/pom.xml
webforj-components/webforj-applayout/src/main/java/com/webforj/component/layout/applayout/AppDrawerToggle.java
webforj-components/webforj-applayout/src/test/java/com/webforj/component/layout/applayout/AppDrawerToggleTest.java

`AppDrawerToggle` is an Icon button that can be use to toggle the drawer in app-layout component. 
```java
AppLayout layout = new AppLayout();
layout.addToHeader(new AppDrawerToggle());
```

feat: add `AppDrawerToggle` component

---

webforj-foundation/src/main/java/com/webforj/Bootstrap.java
webforj-foundation/src/main/java/com/webforj/component/element/ElementComposite.java
webforj-foundation/src/main/java/com/webforj/conceiver/Conceiver.java
webforj-foundation/src/main/java/com/webforj/conceiver/ConceiverProvider.java
webforj-foundation/src/main/java/com/webforj/conceiver/DefaultConceiver.java
webforj-foundation/src/main/java/com/webforj/conceiver/exception/ConceiverException.java
webforj-foundation/src/test/java/com/webforj/component/element/ElementCompositeTest.java
webforj-foundation/src/test/java/com/webforj/conceiver/DefaultConceiverTest.java
webforj-foundation/src/test/java/com/webforj/conceiver/EventWithTwoArgs.java

The PR introduces the `Conceiver` package to abstract object instantiation. Applications can provide their own implementation of the `Conceiver` to integrate with other dependency injection (DI) frameworks. The implementation should be able to create any type of object, or fall back to default implementations when necessary. This service is selected early in the application's lifecycle, during the bootstrap phase, ensuring that the app and all its components are created using this service. This work lays the foundation for managing component creation in webforJ routing.
```java
package samples;
import org.springframework.beans.factory.ObjectProvider;
import org.springframework.context.ApplicationContext;
import org.springframework.context.annotation.AnnotationConfigApplicationContext; …
```

feat: add `Conceiver` to abstract objects instantiation

---

webforj-foundation/src/main/java/com/webforj/component/SlotRegistry.java

fix: setting a component to a slot with an existing component throws expcetion

---

webforj-foundation/src/main/java/com/webforj/Environment.java

Fixes [Issue-784](https://github.com/webforj/webforj/issues/784)

fix: use getId instead of getName since the name of the thread can change

---

pom.xml
webforj-foundation/pom.xml
webforj-foundation/src/main/java/com/webforj/Bootstrap.java
webforj-foundation/src/main/java/com/webforj/Environment.java
webforj-foundation/src/main/resources/bbj/webforj.bbj
webforj-foundation/src/main/resources/webforj-default.conf
webforj-foundation/src/test/java/com/webforj/EnvironmentTest.java

The `webforj.conf` file manages several global settings for webforJ.

feat: support `webforj.conf`

---

webforj-foundation/src/main/java/com/webforj/error/StackTracePageBuilder.java

fix: correct typo in error message heading

---

webforj-components/webforj-login/src/main/java/com/webforj/component/login/Login.java

fix: Typo in Enum Declaration: `SILIENT` Instead of `SILENT`

---

webforj-components/webforj-icons/src/main/java/com/webforj/component/icons/Icon.java

feat: add HasTooltip interface to Icon class

---

webforj-components/webforj-icons/src/main/java/com/webforj/component/icons/Icon.java

feat: implement the `HasSize` interface in Icon component

---

webforj-data/src/main/java/com/webforj/data/repository/CompositeComparator.java
webforj-data/src/test/java/com/webforj/data/repository/CompositeComparatorTest.java

fix: `CompositeComparator` does not handle null values gracefully

---

webforj-foundation/src/main/java/com/webforj/component/field/DateTimeField.java
webforj-foundation/src/main/java/com/webforj/component/field/TimeField.java
webforj-foundation/src/test/java/com/webforj/component/field/DateTimeFieldTest.java
webforj-foundation/src/test/java/com/webforj/component/field/TimeFieldTest.java

fix: DateTimeField and TimeField must truncate seconds

---

webforj-components/webforj-icons/src/main/java/com/webforj/component/icons/Icon.java
webforj-components/webforj-icons/src/main/java/com/webforj/component/icons/IconExpanse.java

feat: add support for configuring Icon expansion

---

webforj-foundation/src/main/java/com/webforj/component/list/ComboBox.java
webforj-foundation/src/test/java/com/webforj/component/list/ComboBoxTest.java

fix: ComboBox with custom values disabled now behaves consistently with a ChoiceBox

---

webforj-foundation/src/main/java/com/webforj/component/field/DwcTextField.java
webforj-foundation/src/test/java/com/webforj/component/field/DwcTextFieldTest.java

feat: allow TextFields to set the the autocomplete attribute

---

webforj-plugins/webforj-install-bbj-plugin/pom.xml

Cleaned up webforj-engine dependency declaration.  Removed exclusions.  Removed additional declarations which previously provided a library version which did not have the vulernability

resolves #883

---

webforj-foundation/src/main/java/com/webforj/component/element/Element.java

revert: register Element defined event listener only once to optimize performance (#860)

---

webforj-foundation/src/main/java/com/webforj/App.java
webforj-foundation/src/main/java/com/webforj/Environment.java
webforj-foundation/src/main/java/com/webforj/utilities/Assets.java
webforj-foundation/src/test/java/com/webforj/utilities/AssetsTest.java

For context: https://bugzilla.basis.cloud/show_bug.cgi?id=35763

fix: webforj does not separate routes when multiple WARs are deployed in the same server

---

webforj-components/webforj-table/src/main/java/com/webforj/component/table/Table.java
webforj-components/webforj-table/src/test/java/com/webforj/component/table/TableTest.java

fix: Programmatically updating table sorting doesn't work when using server-side sorting.

---

.vscode/settings.json
webforj-bom/pom.xml
webforj-components/pom.xml
webforj-components/webforj-infinite-scroll/pom.xml
webforj-components/webforj-infinite-scroll/src/main/java/com/webforj/component/infinitescroll/InfiniteScroll.java
webforj-components/webforj-infinite-scroll/src/main/java/com/webforj/component/infinitescroll/event/InfiniteScrollEvent.java
webforj-components/webforj-infinite-scroll/src/test/java/com/webforj/component/infinitescroll/InfiniteScrollTest.java
webforj-components/webforj-refresher/pom.xml
webforj-components/webforj-refresher/src/main/java/com/webforj/component/refresher/Refresher.java
webforj-components/webforj-refresher/src/main/java/com/webforj/component/refresher/RefresherI18n.java
webforj-components/webforj-refresher/src/main/java/com/webforj/component/refresher/event/RefresherRefreshEvent.java
webforj-components/webforj-refresher/src/test/java/com/webforj/component/refresher/RefresherTest.java
webforj-foundation/src/main/java/com/webforj/utilities/Assets.java
webforj-report-aggregate/pom.xml
webforj/pom.xml

https://github.com/user-attachments/assets/82511af9-fbeb-4b87-b483-1cab39310202
```java
import java.util.Random;
import java.util.concurrent.atomic.AtomicInteger;
import com.webforj.annotation.InlineStyleSheet;
import com.webforj.component.Composite;
import com.webforj.component.html.elements.Div;
import com.webforj.component.html.elements.H1;
import com.webforj.component.icons.FeatherIcon;
import com.webforj.component.icons.Icon;
import com.webforj.component.infinitescroll.InfiniteScroll;
import com.webforj.component.layout.applayout.AppLayout;
import com.webforj.component.layout.applayout.AppLayout.DrawerPlacement;
import com.webforj.component.layout.flexlayout.FlexLayout;
import com.webforj.component.layout.toolbar.Toolbar;
import com.webforj.component.refresher.Refresher;
import …
```

feat: add `infinite-scroll` & `refresher` components

---

webforj-components/webforj-table/src/main/java/com/webforj/component/table/Table.java
webforj-components/webforj-table/src/test/java/com/webforj/component/table/TableTest.java

Cells and rows can be dynamically styled using custom part names determined by the application's logic and the table data. 
For instance, this feature enables you to highlight specific rows and apply unique styles to individual columns.
```java
import java.util.ArrayList;
import java.util.List;
import com.webforj.annotation.InlineStyleSheet;
import com.webforj.component.Composite;
import com.webforj.component.button.Button;
import com.webforj.component.button.ButtonTheme;
import com.webforj.component.layout.flexlayout.FlexDirection;
import com.webforj.component.layout.flexlayout.FlexLayout;
import com.webforj.component.table.Table;
import com.webforj.router.annotation.Route;
@Route("/")
@InlineStyleSheet(/* css */ """
dwc-table::part(row-even) {
background-color: var(--dwc-color-default); …
```

feat: allow to dynamically style table rows and cells

---

webforj-components/webforj-table/src/main/java/com/webforj/component/table/Table.java
webforj-components/webforj-table/src/test/java/com/webforj/component/table/TableTest.java

fix: table `getSelectedKeys` does not return the original repository keys

---

webforj-foundation/src/main/java/com/webforj/App.java
webforj-foundation/src/main/java/com/webforj/AppLifecycleListener.java
webforj-foundation/src/main/java/com/webforj/AppLifecycleListenerRegistry.java
webforj-foundation/src/main/java/com/webforj/Bootstrap.java
webforj-foundation/src/main/java/com/webforj/Environment.java
webforj-foundation/src/test/java/com/webforj/AppLifecycleListenerTest.java
webforj-foundation/src/test/java/com/webforj/EnvironmentTest.java

- Add onWillCreate and onDidCreate to AppLifecycleListener
- Enable config modification before app instantiation
- Move config loading to Environment.init()
- Single ServiceLoader scan in Bootstrap

feat: add early lifecycle hooks for config management

---

webforj-spring/webforj-spring-integration/src/main/java/com/webforj/spring/SpringConceiver.java

 fix: App instances should not be reused in spring when Routify is disabled
