pom.xml
Maven plugins are no dependencies for production code. Only used during the build.
=> Fixed #136 - Remove plugin dependencies from the pom file

src/main/java/org/dwcj/controls/slider/Slider.java
Removed the inverted functionality as this seemed to be ineffective in DWCJ, and removed the functionality from setText, though the function still shows up in IDE autocompletion as it's in AbstractDwcControl.
=> Slider fixes

pom.xml
- removed the configuration for finalName because the version is already given by default behaviour.
=> Fixed #150 - Fix WARNING in build

src/main/java/org/dwcj/controls/tabcontrol/TabControl.java
This implements the most basic Tab Control handling methods to put a DIV under a tab.
There seems to be a problem though which I had noticed in BBj already: When adding a ChildWindow to a tab, DWC or BBj seems to destroy the "display" style of the ChildWindow that's added. See this sample:
```java
package fiddle;
import org.dwcj.App;
import org.dwcj.controls.button.Button;
import org.dwcj.controls.label.Label;
import org.dwcj.controls.panels.AppPanel;
import org.dwcj.controls.panels.Div;
import org.dwcj.controls.tabcontrol.TabControl;
import org.dwcj.exceptions.DwcException;
public class TabControlSample extends App {
@Override
public void run() throws DwcException {
AppPanel p = new AppPanel();
TabControl tab = new TabControl();
p.add(tab);
// add div immediately
Div panel1 = new Div(); …
```
=> add most basic methods to handle DIV panels inside a tab control

src/main/java/org/dwcj/controls/combobox/ComboBox.java
AppPanel panel = new AppPanel();
ComboBox combo = new ComboBox();
combo.addItem("Test 1", "Test 1");
combo.addItem("Test 2", "Test 2");
combo.addItem("Test 3", "Test 3");
combo.selectIndex(1);
panel.add(combo);
=> Added selected index to catchup method

dwcj-engine/src/main/java/org/dwcj/Page.java, dwcj-engine/src/main/java/org/dwcj/annotations/AnnotationProcessor.java, dwcj-engine/src/main/java/org/dwcj/annotations/InlineJavaScript.java, dwcj-engine/src/main/java/org/dwcj/annotations/InlineStyleSheet.java, dwcj-engine/src/main/java/org/dwcj/annotations/JavaScript.java, dwcj-engine/src/main/java/org/dwcj/annotations/StyleSheet.java, dwcj-engine/src/main/java/org/dwcj/util/Assets.java
@mhawkinsbasis 
The PR is to improve assets managing.
1. `addStyleSheet`, `addJavaScript` and `addLink` supports now the `webserver://` protocol. 
For instance:
``` java
addStyleSheet('webserver://static/css/style.css');
``` 
In this case the URL points to the folder of the running application under jetty's htdocs (`bbx/htdocs/myapp`). 
2. `addInlineStyleSheet` & `addInlineJavaScript` supports now the `context://` protocol. 
For instance:
```java
addInlineJavaScript('"context://public/js/jquery.js"');
```
In this case the URL points to the root of the `resources` folder of your application.
3. `InlineStyleSheet` & `InlineJavaScript` annotations do not support the `local` attribute anymore. Use the `context://` protocol. 
4. `StyleSheet` & `JavaScript` annotations rename `url` attribute to …
=> refactor: intrdouce context and webserver protocols

dwcj-engine/src/main/java/org/dwcj/controls/tabcontrol/TabControl.java
Will need to go back and implement a Java representation for the tab control which can be queried independent of the BBj Control for testing purposes, and to allow for the panels to be returned (as the BBj API method returns a BBjControl). Will open an issue for this. For now, this fix will have methods interact with the ArrayList before the control is added to the panel, and the underlying BBj TabControl after it has been added.
=> Tab control update

dwcj-engine/src/main/java/org/dwcj/annotations/AnnotationProcessor.java, dwcj-engine/src/main/java/org/dwcj/annotations/STConfiuration.java, dwcj-engine/src/main/java/org/dwcj/environment/StringTable.java, dwcj-engine/src/main/resources/bbj/dwcj.bbj
The PR adds the `STConfiuration` annotation:
The `STConfiuration` is an annotation to manipulate the global [`StringTable`](https://github.com/DwcJava/engine/blob/main/dwcj-engine/src/main/java/org/dwcj/environment/StringTable.java).
This annotation can be used multiple times to define multiple configuration and it can be used at the Application or the controls level. Application level configurations will always override the controls level configurations.
Certain configurations cannot be overridden at the application level when they are defined in the `config.bbx` file. Like `DEBUG` flag
The annotation will guarantee the order of which the configuration are applied unlike using the  [`StringTable`](https://github.com/DwcJava/engine/blob/main/dwcj-engine/src/main/java/org/dwcj/environment/S …
=> feat: adds the `STConfiuration` annotation

.github/workflows/maven-test.yml
The PR adds a GitHub action to run the unit tests with `dwcjjava` docker image and BBj nightly
=> ci: add maven test action

dwcj-engine/src/main/java/org/dwcj/component/AbstractOptionInput.java, dwcj-engine/src/test/java/org/dwcj/component/AbstractOptionInputTest.java
The CheckBox expanse API uses the `org.dwcj.component.Expanse` now instead of the internal defined Expanse Enum
=> refactor: `CheckBox` expanse API should use  the `org.dwcj.component.Expanse`

dwcj-engine/src/main/java/org/dwcj/component/AbstractDwcComponent.java, dwcj-engine/src/main/java/org/dwcj/component/checkbox/CheckBox.java, dwcj-engine/src/main/java/org/dwcj/component/radiobutton/RadioButton.java, dwcj-engine/src/main/java/org/dwcj/exceptions/DwcjRestrictedAccessException.java, dwcj-engine/src/test/java/org/dwcj/component/AbstractDwcComponentMock.java, dwcj-engine/src/test/java/org/dwcj/component/AbstractDwcComponentTest.java
The PR introduces the necessary API that enables components to have control over which attributes and properties are restricted and cannot be modified by the setAttribute/setProperty APIs
=> feat: add restricted properties an attributes API 

dwcj-engine/src/main/java/org/dwcj/component/Component.java, dwcj-engine/src/main/java/org/dwcj/component/ComponentLifecycleObserver.java, dwcj-engine/src/test/java/org/dwcj/component/ComponentTest.java
The component class allow now adding external lifecycle observers to be notified when the component is created or destroyed
=> feat: Add component LifecycleObserver support

dwcj-engine/src/main/java/org/dwcj/PendingResult.java, dwcj-engine/src/test/java/org/dwcj/PendingResultTest.java
The method Returns a new `PendingResult` that is completed when all of the given `PendingResults` complete. If
any of the given `PendingResult` complete exceptionally, then the returned `PendingResult` also does so.
=> feat: add `PendingResult::allOf` method

dwcj-engine/src/main/java/org/dwcj/component/Component.java, dwcj-engine/src/main/java/org/dwcj/component/DwcComponent.java
The client component ID is auto generated ID by BBj. This method  Retrieves the ID of the component's client-side counterpart.  If the component has a client-side counterpart, this method returns the ID of that component on the client side. If the component does not have a client-side counterpart, this method returns `null`.
=> feat: add `Component::geClientComponentId` method

dwcj-engine/src/main/java/org/dwcj/component/drawer/Drawer.java, dwcj-engine/src/test/java/org/dwcj/component/drawer/DrawerTest.java
@MatthewHawkins please update the drawer docs, the PR:
1. Remove style methods (setSize and setMaxWidth). Css variables must be used for this (Keep the current docs, just explain the way to do it in css variables) 
2. Add support for the  `title`, `header-actions` and `footer` slots
```java
public class DrawerDemo extends App {
Drawer drawer = new Drawer("Drawer");
Element title = new Element("p", "This is a Drawer component!");
Button button = new Button("Click me!");
@Override
public void run() throws DwcjException {
Frame app = new Frame();
app.add(drawer);
drawer.open();
drawer.add(title);
drawer.addToFooter(button.setTheme(ButtonTheme.PRIMARY));
}
}
```
=> feat(drawer): add support for `title`, `header-actions` and `footer` slots

dwcj-engine/src/main/java/org/dwcj/App.java, dwcj-engine/src/main/java/org/dwcj/annotation/AnnotationProcessor.java, dwcj-engine/src/main/java/org/dwcj/utilities/WelcomeApp.java
@MatthewHawkins
This enhancement  is for the documentation site. With this update, applications can automatically detect the application theme based on the query parameter `__theme__`. For this feature to function, the STBL configuration `PARSE_REQUEST_THEME=1` must be included in `config.bbx`. Please test this adjustment with the documentation and provide feedback regarding any encountered issues.
=> feat: allow apps to apply themes from query params

webforj-foundation/src/main/java/com/webforj/Interval.java, webforj-foundation/src/test/java/com/webforj/IntervalTest.java
webforJ Timer implementation based on BBj timers
```java
Interval interval = new Interval(0.1f, new EventListener<Interval.ElapsedEvent>() {
private int progress = 0;
@Override
public void onEvent(Interval.ElapsedEvent event) {
progress++;
bar.setValue(progress);
if (progress >= bar.getMax()) {
event.getInterval().stop();
}
}
});
interval.start();
```
=> feat: Add webforJ Interval similar to Swing Timer

webforj-foundation/src/main/java/com/webforj/component/list/DwcList.java, webforj-foundation/src/main/java/com/webforj/component/optioninput/DwcOptionInput.java, webforj-foundation/src/main/java/com/webforj/concern/HasHelperText.java, webforj-foundation/src/test/java/com/webforj/component/list/DwcListTest.java, webforj-foundation/src/test/java/com/webforj/component/optioninput/DwcOptionInputTest.java, webforj-foundation/src/test/java/com/webforj/concern/ConcernComponentMock.java, webforj-foundation/src/test/java/com/webforj/concern/HasHelperTextTest.java
All List and Option Input components support optional helper text that appears beneath the input, providing relevant information or a description of the input or option.
For instance: 
```java
ChoiceBox choice = new ChoiceBox("Department");
choice.insert("Electronics", "Health and Beauty", "Fashion", "Kitchen", "Furniture",
"Pet Supplies", "Toys and Games");
choice.selectIndex(0);
choice.setHelperText("What is your department?");
```
=> feat: add helper text support to components list and optioninput components

webforj-foundation/src/main/java/com/webforj/Page.java, webforj-foundation/src/test/java/com/webforj/PageTest.java
```java
Page.getCurrent().open("https://webforj.com/", "webforJ",
"popup,left=100,top=100,width=600,height=600");
```
closes #615
=> feat: add open methods to Page class for opening URLs

webforj-foundation/src/main/java/com/webforj/App.java
The following methods have been marked as deprecated and are scheduled for removal in version **`v25.00`**. Alternatives for each are provided:
| Deprecated Method                | Deprecated Since | Scheduled for Removal | Use Instead         |
|----------------------------------|------------------|-----------------------|---------------------|
| `public static Page getPage()`   | 24.10            | 25.00                 | `Page.getCurrent()` |
| `public static Request getRequest()` | 24.10        | 25.00                 | `Request.getCurrent()` |
| `public static String getProtocol()` | 24.02        | 25.00                 | `Request.getProtocol()` |
| `public static String getHost()` | 24.02            | 25.00                 | `Request.getHost()` |
| `public static String getPort()` | …
=> refactor: mark deprecated methods in `App.java`

webforj-foundation/src/main/java/com/webforj/App.java
see #494 , #624
| Deprecated Method                  | Deprecated Since | Scheduled for Removal | Use Instead                   |
|------------------------------------|------------------|-----------------------|-------------------------------|
| `public static void consoleLog(String output)` | 24.10            | 25.00                 | `BrowserConsole.log(String)`   |
| `public static void consoleError(String output)` | 24.10            | 25.00                 | `BrowserConsole.error(String)` |
=> refactor: mark `consoleLog` and `consoleError` methods deprecated

webforj-foundation/src/main/java/com/webforj/component/element/PropertyDescriptorInfo.java, webforj-foundation/src/main/java/com/webforj/component/element/PropertyDescriptorScanner.java, webforj-foundation/src/main/java/com/webforj/component/element/PropertyDescriptorTester.java, webforj-foundation/src/main/java/com/webforj/component/element/annotation/IgnoreProperty.java, webforj-foundation/src/main/java/com/webforj/component/element/annotation/PropertyExclude.java, webforj-foundation/src/main/java/com/webforj/component/element/annotation/PropertyMethods.java
Adds two new annotations, `PropertyExclude` and `PropertyMethods`, to the webforj component element package. These annotations are used to provide hints to the `PropertyDescriptorTester` class. The `PropertyExclude` annotation is used to indicate that a property should be ignored, while the `PropertyMethods` annotation is used to specify the getter and setter methods for a property. 
```java
@PropertyMethods(setter = "setVisible", getter = "isVisible")
private final PropertyDescriptor<Boolean> openedProp =
PropertyDescriptor.property("opened", false);
@PropertyMethods(target = LoadingSpinner.class, setter = "setVisible", getter = "isVisible")
private final PropertyDescriptor<Boolean> suppressSpinnerProp =
PropertyDescriptor.property("suppressSpinner", false);
@PropertyExclude
private …
```
=> feat: enable `PropertyDescriptorTester` to support hinting for proprety setters and getters.

webforj-foundation/src/main/java/com/webforj/component/DwcComponent.java, webforj-foundation/src/test/java/com/webforj/component/DwcComponentTest.java
The PR implements the `HasHtml` interface in `DwcComponent` to support setting HTML text. Setting HTML text that is not specifically wrapped with `<html>` using the `setText` method is no longer possible.
```java
// Valid
Button home = new Button("""
<html>
<dwc-icon name='home'></dwc-icon>
</html>
""");
```
```java
// Not Valid
Button home = new Button("""
<dwc-icon name='home'></dwc-icon>
""");
```
=> feat: add support for setting HTML text in `DwcComponent`

webforj-foundation/src/main/java/com/webforj/component/htmlcontainer/HtmlContainer.java
since `24.10`, for removal in `25.00`. Use  `Element` instead for custom content or use `Iframe` component for embedding pages
=> refactor: deprecate HtmlContainer component

webforj-foundation/src/main/java/com/webforj/Page.java, webforj-foundation/src/main/java/com/webforj/event/page/PageUnloadEvent.java, webforj-foundation/src/main/java/com/webforj/event/page/PageUnloadEventHandler.java, webforj-foundation/src/test/java/com/webforj/PageTest.java
closes #664 
```java
@Override
Page.getCurrent().onUnload((event) -> {
System.out.println("Page is unloading, webforj is shutting down");
});
}
}
```
=> feat: add page unload event listener to Page class

webforj-foundation/src/main/java/com/webforj/App.java, webforj-foundation/src/main/resources/bbj/webforj.bbj
The PR introduces more lifecycle methods and ensures that the `terminate` method is called when the browser unloads the page. and deprecate the `cleanup` method
```java
@Override
protected void onWillRun() {
System.out.println("App will run");
}
@Override
System.out.println("App is running");
}
@Override
protected void onDidRun() {
System.out.println("App did run");
}
@Override
protected void onWillTerminate() {
System.out.println("App will terminate");
}
@Override
protected void onDidTerminate() {
System.out.println("App did terminate");
}
}
```
=> feat: introduce app lifecycle

webforj-components/webforj-terminal/src/main/java/com/webforj/component/terminal/Terminal.java, webforj-components/webforj-terminal/src/test/java/com/webforj/component/terminal/TerminalTest.java
The PR introduces new method signatures for `write` and `writeln`, allowing them to accept a callback that is invoked once the parser has finished writing the data.
```java
term.write("", data -> term.writeln("Load test completed"));
term.writeln("", data -> term.write("$ "));
```
=> feat: allow terminal write methods to accept a complete callback

webforj-foundation/src/main/java/com/webforj/component/DwcComponent.java, webforj-foundation/src/test/java/com/webforj/component/DwcComponentTest.java
=> fix: `isReadOnly` does accurately reflect read-only status

webforj-dispatcher/src/main/java/com/webforj/dispatcher/EventDispatcher.java
=> fix: `EventDispatcher` Catching of `ClassCastException` Leading to Confusing Error Messages

webforj-foundation/src/main/java/com/webforj/Page.java, webforj-foundation/src/main/java/com/webforj/component/element/annotation/ElementAnnotationProcessor.java, webforj-foundation/src/main/java/com/webforj/component/element/annotation/EventOptionsAnnotationProcessor.java, webforj-foundation/src/main/java/com/webforj/component/element/event/ElementEventOptions.java, webforj-foundation/src/main/java/com/webforj/component/event/EventSinkListenerRegistry.java, webforj-foundation/src/main/java/com/webforj/event/page/PageEvent.java, webforj-foundation/src/main/java/com/webforj/event/page/PageEventOptions.java, webforj-foundation/src/main/java/com/webforj/sink/page/PageEventSink.java, webforj-foundation/src/main/java/com/webforj/sink/page/PageEventSinkRegistry.java, webforj-foundation/src/test/java/com/webforj/PageTest.java, webforj-foundation/src/test/java/com/webforj/sink/page/PageEventSinkTest.java
The PR adds support for registering HTML events directly through the page instance without needing an element or a bridge.
```java
PageEventOptions pageEventOptions = new PageEventOptions();
pageEventOptions.addData("clientX", "event.clientX");
pageEventOptions.addData("clientY", "event.clientY");
ListenerRegistration<PageEvent> r1 = Page.getCurrent().addEventListener("click", e -> {
int x = (int) e.getData().get("clientX");
int y = (int) e.getData().get("clientY");
console().log("x: " + x + ", y: " + y);
}, pageEventOptions);
```
=> feat: support HTML event registration via the page instance

webforj-foundation/src/main/java/com/webforj/component/DwcFocusableMixin.java
=> fix: components that are not focusable are not being removed from the tab order

webforj-foundation/src/main/java/com/webforj/bridge/BBjWindowAdapter.java
this fixing the interop with BBj which was broken for a while.
=> fix: BBjWindowAdapter now needs additional call to create()

webforj-foundation/src/main/java/com/webforj/component/SlotRegistry.java, webforj-foundation/src/main/java/com/webforj/component/element/Element.java, webforj-foundation/src/test/java/com/webforj/component/SlotRegistryTest.java, webforj-foundation/src/test/java/com/webforj/component/element/ElementTest.java
Add `SlotRegistry`  to manage components by associating them with named slots.
=> refactor: add `SlotRegistry` to manage components in slots

webforj-foundation/src/main/java/com/webforj/component/DwcComponent.java, webforj-foundation/src/main/java/com/webforj/component/SlotAssigner.java, webforj-foundation/src/main/java/com/webforj/component/SlotRegistry.java, webforj-foundation/src/main/java/com/webforj/component/button/Button.java, webforj-foundation/src/main/java/com/webforj/component/button/DwcButton.java, webforj-foundation/src/main/java/com/webforj/component/field/DwcField.java, webforj-foundation/src/main/java/com/webforj/component/list/DwcSelectDropdown.java, webforj-foundation/src/main/java/com/webforj/component/tabbedpane/Tab.java, webforj-foundation/src/main/java/com/webforj/component/tabbedpane/TabChangeListener.java, webforj-foundation/src/main/java/com/webforj/component/tabbedpane/TabbedPane.java, webforj-foundation/src/main/java/com/webforj/concern/HasPrefix.java, webforj-foundation/src/main/java/com/webforj/concern/HasPrefixAndSuffix.java, webforj-foundation/src/main/java/com/webforj/concern/HasSuffix.java, webforj-foundation/src/test/java/com/webforj/component/DwcComponentTest.java, webforj-foundation/src/test/java/com/webforj/component/SlotAssignerTest.java, webforj-foundation/src/test/java/com/webforj/component/SlotRegistryTest.java, webforj-foundation/src/test/java/com/webforj/component/button/DwcButtonTest.java, webforj-foundation/src/test/java/com/webforj/component/field/DwcFieldTest.java, webforj-foundation/src/test/java/com/webforj/component/list/DwcSelectDropdownTest.java, webforj-foundation/src/test/java/com/webforj/component/tabbedpane/TabbedPaneTest.java, webforj-foundation/src/test/java/com/webforj/concern/ConcernComponentMock.java, webforj-foundation/src/test/java/com/webforj/concern/HasPrefixAndSuffixTest.java
The PR adds support for prefix and suffix slots in the following components:
1. Button
2. ChoiceBox
3. ComboBox
4. TabbedPane
5. All Field Types
```java
Button icon = new Button(new Img("http://localhost:8888/joystick.png"));
Button btn = new Button("Click me");
btn.setPrefixComponent(new Img("http://localhost:8888/joystick.png"));
btn.setSuffixComponent(new Img("http://localhost:8888/joystick.png"));
```
```java
MaskedDateField dateField = new MaskedDateField("Chooser Date", LocalDate.now());
dateField.setPrefixComponent(new Img("http://localhost:8888/joystick.png"));
dateField.setSuffixComponent(new Img("http://localhost:8888/joystick.png"));
```
```java
TabbedPane pane = new TabbedPane();
pane.addTab(new Tab("Dashboard", new Img("http://localhost:8888/joystick.png")));
pane.addTab(new …
```
=> feat: allow setting prefix and suffix slots for supported components

webforj-components/pom.xml, webforj-components/webforj-toolbar/pom.xml, webforj-components/webforj-toolbar/src/main/java/com/webforj/component/layout/toolbar/Toolbar.java, webforj-components/webforj-toolbar/src/test/java/com/webforj/component/layout/toolbar/ToolbarTest.java, webforj-report-aggregate/pom.xml, webforj/pom.xml
The PR introduces the `Toolbar` component for use with `AppLayout`, reducing boilerplate code when working with `AppLayout`.
```java
Toolbar toolbar = new Toolbar();
toolbar.addToStart(new AppDrawerToggle());
toolbar.addToTitle(new H1("DWC App"));
toolbar.setTheme(Theme.PRIMARY);
AppLayout layout = new AppLayout();
layout.addToHeader(toolbar);
```
=> feat: add `toolbar` component

webforj-foundation/src/main/java/com/webforj/router/history/Location.java, webforj-foundation/src/test/java/com/webforj/router/history/LocationTest.java
The `Location` should normalize the path when `getFullURI` is invoked
=> fix: normalize path in Location

webforj-components/webforj-columnslayout/src/main/java/com/webforj/component/layout/columnslayout/ColumnsLayout.java
=> fix: `Columnslayout` does not have a default constructor

webforj-foundation/src/main/java/com/webforj/component/field/NumberField.java, webforj-foundation/src/test/java/com/webforj/component/field/NumberFieldTest.java
The NumberField always displays numbers as doubles because the setValue method only accepts doubles. This Improves the component’s behavior to detect if the value can be displayed as an Integer and display it accordingly.
=> fix: `NumberField` display numbers always as doubles

webforj-components/webforj-table/src/main/java/com/webforj/component/table/event/cell/TableCellDoubleClickEvent.java
=> fix: table's cell double click and cell click both fire on single click

webforj-foundation/src/main/java/com/webforj/ProfileDescriptor.java, webforj-foundation/src/main/java/com/webforj/annotation/AnnotationProcessor.java, webforj-foundation/src/main/java/com/webforj/annotation/AppProfile.java, webforj-foundation/src/test/java/com/webforj/ProfileDescriptorTest.java, webforj-foundation/src/test/java/com/webforj/annotation/AnnotationProcessorTest.java
This PR introduces the `@AppProfile` annotation, enabling developers to define key application metadata directly in their code. The annotation supports configuration of properties such as app name, short name, description, theme color, icons, screenshots, and more, streamlining the creation and management of the web app manifest. By automating manifest generation, this feature simplifies the process of building Progressive Web Apps (PWAs) with customizable and user-friendly presentation settings.
```java
@AppProfile(
name = "Zyntric Bank",
shortName = "ZBank",
description = "Zyntric Bank is a simple banking application built with webforj",
screenshots = {
@AppProfile.Screenshot(
src= "ws://img/screenshots/s1.jpg",
sizes = "1080x1920"
)
}
)
public class Application extends App {
}
``` …
=> feat: add `@AppProfile` Annotation for app manifest and meta configuration

webforj-foundation/src/main/java/com/webforj/component/list/ChoiceBox.java, webforj-foundation/src/main/java/com/webforj/component/list/DwcSelectDropdown.java, webforj-foundation/src/main/java/com/webforj/component/list/ListBox.java, webforj-foundation/src/test/java/com/webforj/component/list/ChoiceBoxTest.java, webforj-foundation/src/test/java/com/webforj/component/list/DwcListTest.java, webforj-foundation/src/test/java/com/webforj/component/list/ListBoxTest.java
The list controls have inherited some unclear behavior from BBj. Here's how the current BBj methods work:
1. **ListBox**:  
- `setText`: Accepts a linefeed-delimited string to populate the list.  
- `getText`: Returns the currently selected items as a comma-separated string.
2. **ListButton**:  
- `setText`: Accepts a linefeed-delimited string to populate the list.  
- `getText`: Returns the currently selected item.
3. **ListEdit**:  
- `setText`: Sets the input text and selects the item if it exists in the list.  
- `getText`: Returns the input text. If the text matches an item in the list, it returns the selected item. Otherwise, it simply returns the input text.
This PR refactors the behavior of the `ListBox` and `ChoiceBox` to standardize the `setText` and `getText` methods. Now, they …
=> refactor: streamline the behavior of list components to set/get selected items

webforj-components/webforj-html-elements/src/main/java/com/webforj/component/html/elements/Img.java, webforj-foundation/src/main/java/com/webforj/annotation/AnnotationProcessor.java, webforj-foundation/src/main/java/com/webforj/annotation/AppProfile.java, webforj-foundation/src/main/java/com/webforj/utilities/Assets.java, webforj-foundation/src/test/java/com/webforj/utilities/AssetsTest.java
By default, webforj serves icons from the `resources/icons/` directory. You can change the endpoint name by setting the `webforj.iconsDir` property in the webforj configuration file. The default endpoint is `icons/`.
The icons endpoint accepts the icon file name as a path parameter with a specified size. For example, `icons://icon-144x144.png` will return the icon with a size of 144x144. The base image should be placed in the `resources/icons/` directory and named `icon.png`.
Additionally, you can add padding or a background color to the icon using the following query parameters:
- **`padding`**: The padding around the icon, specified as a number between 0 and 1.  
For example, `icons://icon-144x144.png?padding=.3` adds a 30% padding around the icon.
- **`background`**: The background …
=> feat: Add support for icons URL handling in Assets and related components

webforj-components/webforj-table/src/main/java/com/webforj/component/table/Column.java, webforj-components/webforj-table/src/main/java/com/webforj/component/table/Table.java, webforj-components/webforj-table/src/main/java/com/webforj/component/table/event/TableSortChangeEvent.java, webforj-components/webforj-table/src/test/java/com/webforj/component/table/TableTest.java, webforj-components/webforj-table/src/test/java/com/webforj/component/table/event/TableSortChangeEventTest.java
Starting with webforj 25.00, tables now support single-column sorting by default. Clicking on a column header will sort that column and automatically clear sorting from all other columns.
To enable multi-column sorting, use the new API method `setMultiSorting(boolean)`. Setting it to `true` allows users to sort multiple columns simultaneously. When multi-sorting is enabled, the table will visually indicate the sort order by numbering the sorted columns, making it easy for users to track the sorting sequence.
When configuring server-side sorting, the user must call `setSortOrder` on the columns that should be sorted to define their priority. Otherwise, the table will sort the data based on the default column order.
```java
import java.util.List;
import com.webforj.component.Composite; …
```
=> feat: Add table sort index functionality and enable single column sorting mode

webforj-foundation/src/main/java/com/webforj/component/progressbar/ProgressBar.java
=> feat: add support for hiding the progress bar text by passing an empty string to the `setText` method.

webforj-components/webforj-table/src/main/java/com/webforj/component/table/Table.java, webforj-components/webforj-table/src/test/java/com/webforj/component/table/TableTest.java
Add new table methods to simplify styling: 
1. **setBordersVisible** :  Sets the visible borders of the table. The visible borders are the borders that are drawn around the table and between the rows and columns. The default value is `Border.ROWS` and `Border.AROUND`.
```java
// enable all borders
table.setBordersVisible(EnumSet.of(Table.Border.AROUND, Table.Border.COLUMNS, Table.Border.ROWS));
// no borders
table.setBordersVisible(EnumSet.noneOf(Table.Border.class));
```
2. **setStriped**:  The striped property is used to apply a background color to every other row in the table, creating a striped effect. This can improve readability by making it easier to distinguish  between adjacent rows of data.
```java
table.setStriped(true);
```
=> feat: add support for customizable table borders and striped rows

.vscode/settings.json, webforj-bom/pom.xml, webforj-components/pom.xml, webforj-components/webforj-desktop-notification/pom.xml, webforj-components/webforj-desktop-notification/src/main/java/com/webforj/component/desktopnotification/DesktopNotification.java, webforj-components/webforj-desktop-notification/src/main/java/com/webforj/component/desktopnotification/event/DesktopNotificationClickEvent.java, webforj-components/webforj-desktop-notification/src/main/java/com/webforj/component/desktopnotification/event/DesktopNotificationCloseEvent.java, webforj-components/webforj-desktop-notification/src/main/java/com/webforj/component/desktopnotification/event/DesktopNotificationErrorEvent.java, webforj-components/webforj-desktop-notification/src/main/java/com/webforj/component/desktopnotification/event/DesktopNotificationEvent.java, webforj-components/webforj-desktop-notification/src/main/java/com/webforj/component/desktopnotification/event/DesktopNotificationOpenEvent.java, webforj-components/webforj-desktop-notification/src/test/java/com/webforj/component/desktopnotification/DesktopNotificationTest.java, webforj-report-aggregate/pom.xml, webforj/pom.xml
The Notification component is used to configure and display **Native** desktop notifications to the user.
https://github.com/user-attachments/assets/4658f593-3d71-42c5-953c-f15583e062b9
=> feat: add experimental support to desktop notifications 

webforj-foundation/src/main/java/com/webforj/component/element/Element.java
When a component is assigned to a slot, the element first renders the component in the parent window before moving it to the designated slot. This process results in layout shifting, where elements are briefly rendered in the wrong location before being moved to their named slots. These shifts degrade performance and increase browser workload. To mitigate this, temporarily hide the components until they are fully moved, then display them again.
=> fix: Adding components to element slots causes layout shifts

webforj-foundation/src/main/java/com/webforj/App.java, webforj-foundation/src/main/java/com/webforj/AppLifecycleListener.java, webforj-foundation/src/main/java/com/webforj/AppLifecycleListenerRegistry.java, webforj-foundation/src/main/java/com/webforj/annotation/AppListenerPriority.java, webforj-foundation/src/test/java/com/webforj/AppLifecycleListenerTest.java
Implement ServiceLoader-based lifecycle listener mechanism for App instances, allowing external components to observe and react to App lifecycle events.
This enables plugins and extensions to hook into the App lifecycle without modifying core App code, using standard Java ServiceLoader mechanism.
Listeners are called outside of App hook methods (before onDidRun/onDidTerminate, after onWillRun/onWillTerminate) to ensure backward compatibility.
=> feat: add App lifecycle listener support

webforj-spring/webforj-spring-integration/src/main/java/com/webforj/spring/SpringAutoConfiguration.java, webforj-spring/webforj-spring-integration/src/main/java/com/webforj/spring/SpringConfigMerger.java, webforj-spring/webforj-spring-integration/src/main/java/com/webforj/spring/SpringConfigurationProperties.java, webforj-spring/webforj-spring-integration/src/main/java/com/webforj/spring/WebforjConfigBuilder.java, webforj-spring/webforj-spring-integration/src/main/resources/META-INF/services/com.webforj.AppLifecycleListener, webforj-spring/webforj-spring-integration/src/test/java/com/webforj/spring/SpringAutoConfigurationTest.java, webforj-spring/webforj-spring-integration/src/test/java/com/webforj/spring/SpringConfigMergerTest.java, webforj-spring/webforj-spring-integration/src/test/java/com/webforj/spring/SpringConfigurationPropertiesTest.java, webforj-spring/webforj-spring-integration/src/test/java/com/webforj/spring/WebforjConfigBuilderTest.java
| Property | Type | Description |
|----------|------|-------------|
| `webforj.entry` | String | Fully qualified class name of the application entry point (extends `com.webforj.App`) |
| `webforj.debug` | Boolean | Enable debug mode with additional console output and browser exception display |
| `webforj.components` | String | Base path for loading DWC components (e.g., CDN URL) |
| `webforj.locale` | String | Application locale for language, region, date/time/number formatting |
| `webforj.quiet` | Boolean | Disable the loading image during application startup |
| `webforj.reloadOnServerError` | Boolean | Auto-reload page on server errors during hot redeploy (development only) |
| `webforj.clientHeartbeatRate` | String | Interval for client-server heartbeat (e.g., `8s` for dev, `50s`+ …
=> feat: Allow to configure webforj using spring properties file

webforj-components/webforj-toast/pom.xml, webforj-foundation/pom.xml, webforj-foundation/src/main/java/com/webforj/Environment.java, webforj-foundation/src/main/java/com/webforj/environment/SessionObjectTable.java, webforj-foundation/src/test/java/com/webforj/environment/SessionObjectTableTest.java, webforj-spring/webforj-spring-integration/pom.xml
webforJ applications can now access HTTP session data when running in Jakarta 
Servlet 6.1+ containers. Store and retrieve user-specific state across requests.
`SessionObjectTable` follows the `ObjectTable` pattern for consistent storage API.
=> feat: provide API to access `HttpSession.Accessor` and provide `SessionObjectTable`
